/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "ink-black": "#1A1A1A",
        "bit-green": "#C5FF52",
        "primary": "#6f2de1",
        "primary-container": "#884efb",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d1bcff",
        "secondary": "#006b5d",
        "secondary-fixed": "#4dfcdf",
        "secondary-fixed-dim": "#14dfc3",
        "tertiary": "#b5163d",
        "tertiary-container": "#d73453",
        "tertiary-fixed": "#ffdadb",
        "tertiary-fixed-dim": "#ffb2b8",
        "surface": "#fbf9f5",
        "surface-bright": "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-container": "#f0eeea",
        "surface-container-low": "#f5f3ef",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e4e2de",
        "surface-tint": "#7131e3",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#4a4455",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-background": "#1b1c1a",
        "outline": "#7b7487",
        "outline-variant": "#ccc3d8",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-surface": "#30312e",
        "inverse-primary": "#d1bcff",
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['"Atkinson Hyperlegible Next"', 'sans-serif'],
        label: ['"Atkinson Hyperlegible Next"', 'sans-serif'],
      },
      maxWidth: {
        'container': '1200px',
      },
      spacing: {
        'gutter': '24px',
      },
      borderRadius: {
        'sketch': '255px 15px 225px 15px/15px 225px 15px 255px',
      },
      boxShadow: {
        'hard': '6px 6px 0px 0px rgba(26,26,26,1)',
        'hard-sm': '4px 4px 0px 0px rgba(26,26,26,1)',
        'hard-lg': '8px 8px 0px 0px rgba(26,26,26,1)',
        'hard-primary': '6px 6px 0px 0px #884efb',
      },
    },
  },
  plugins: [],
}
